/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Dimension;
import map.Map;


/**
 *
 * @author Lampirg
 */
public final class Main extends javax.swing.JFrame implements MapListener {

    /**
     * Creates new form Main
     */
    public final static int CELL_SIZE = 60;
    
    public final static int DEFAULT_HEIGHT = 10;
    public final static int DEFAULT_WIDTH = 10;
    public final static int DEFAULT_BOMBCOUNT = 10;
    
    private int heightCount = DEFAULT_HEIGHT;
    private int widthCount = DEFAULT_WIDTH;
    private int bombcount = DEFAULT_BOMBCOUNT;
    
    private Map map;
    
    Dimension dimension;
    javax.swing.JFrame settings;
    
    public Main() {
        this(DEFAULT_HEIGHT, DEFAULT_WIDTH, DEFAULT_BOMBCOUNT);
    }
    
    public Main(int heightCount, int widthCount, int bombcount) {
        
        reInitComponents();
        createMap(heightCount, widthCount, bombcount);
        setResizable(false);
    }
    
    public void createMap(int heightCount, int widthCount, int bombcount) {
        if (map != null)
            field.remove(map);
        this.heightCount = heightCount;
        this.widthCount = widthCount;
        this.bombcount = bombcount;
        try {
            map = new Map(heightCount, widthCount, bombcount);
        }
        catch (IllegalArgumentException e) {
            map = new Map(DEFAULT_HEIGHT, DEFAULT_WIDTH, DEFAULT_BOMBCOUNT);
        }
        map.addMapListener(this);
        dimension = new Dimension(widthCount * CELL_SIZE, heightCount * CELL_SIZE);
        field.setMinimumSize(dimension);
        field.add(map);
        pack();
    }
    
//    public void initialize(int heightCount, int widthCount, int bombcount) {
//        removeAll();
//        this.heightCount = heightCount;
//        this.widthCount = widthCount;
//        this.bombcount = bombcount;
//        reInitComponents();
//        Map map = new Map(heightCount, widthCount, bombcount);
//        map.addMapListener(this);
//        field.add(map);
//        setResizable(false);
//    }
    
    @Override
    public void setFlagAmount(int flagAmount) {
        flagState.setText("Number of flags: " + flagAmount);
    }

    @Override
    public void setGameState(String message) {
        gameState.setText(message);
    }
    
    private void reInitComponents() {
        
        //dimension = new Dimension(500, 300);
        initComponents();
        gameState.setText("Good Luck!");
        
        field.setLayout(new java.awt.BorderLayout());
        pack();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        field = new javax.swing.JPanel();
        gameState = new javax.swing.JLabel();
        flagState = new javax.swing.JLabel();
        bombState = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N

        field.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        field.setPreferredSize(new java.awt.Dimension(400, 400));

        javax.swing.GroupLayout fieldLayout = new javax.swing.GroupLayout(field);
        field.setLayout(fieldLayout);
        fieldLayout.setHorizontalGroup(
            fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        fieldLayout.setVerticalGroup(
            fieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        gameState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameState.setText("Good luck!");
        gameState.setAlignmentX(0.5F);
        gameState.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gameState.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        flagState.setText("Number of flags: 0");

        bombState.setText("Number of bombs: " + bombcount);

        jMenu1.setText("File");

        jMenuItem1.setText("Change Size");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addComponent(gameState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(flagState, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(bombState, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flagState)
                    .addComponent(bombState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        settings = new javax.swing.JFrame();
        Settings panel = new Settings(settings);
        panel.addMainFrame(this);
        settings.add(panel);
        settings.pack();
        settings.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bombState;
    private javax.swing.JPanel field;
    private javax.swing.JLabel flagState;
    private javax.swing.JLabel gameState;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

}
